CREATE TABLE aluno (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    excluido BOOLEAN NOT NULL DEFAULT FALSE,
    excluido_em TIMESTAMP WITH TIME ZONE,
    excluido_por VARCHAR(150)
);

CREATE TABLE ano_letivo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ano INTEGER NOT NULL,
    aluno_id BIGINT NOT NULL,
    excluido BOOLEAN NOT NULL DEFAULT FALSE,
    excluido_em TIMESTAMP WITH TIME ZONE,
    excluido_por VARCHAR(150),
    CONSTRAINT fk_ano_letivo_aluno FOREIGN KEY (aluno_id) REFERENCES aluno (id)
);

CREATE TABLE disciplina (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    ano_letivo_id BIGINT NOT NULL,
    excluido BOOLEAN NOT NULL DEFAULT FALSE,
    excluido_em TIMESTAMP WITH TIME ZONE,
    excluido_por VARCHAR(150),
    CONSTRAINT fk_disciplina_ano_letivo FOREIGN KEY (ano_letivo_id) REFERENCES ano_letivo (id)
);

CREATE TABLE tarefa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    data_criacao DATE NOT NULL,
    data_prevista_entrega DATE NOT NULL,
    data_entrega DATE,
    status VARCHAR(30) NOT NULL,
    disciplina_id BIGINT NOT NULL,
    excluido BOOLEAN NOT NULL DEFAULT FALSE,
    excluido_em TIMESTAMP WITH TIME ZONE,
    excluido_por VARCHAR(150),
    CONSTRAINT fk_tarefa_disciplina FOREIGN KEY (disciplina_id) REFERENCES disciplina (id),
    CONSTRAINT ck_tarefa_status CHECK (status IN ('PENDENTE', 'ENTREGUE', 'ENTREGUE_COM_ATRASO')),
    CONSTRAINT ck_tarefa_data_prevista CHECK (data_prevista_entrega >= data_criacao),
    CONSTRAINT ck_tarefa_data_entrega CHECK (data_entrega IS NULL OR data_entrega >= data_criacao)
);

CREATE UNIQUE INDEX uk_aluno_usuario_ativo ON aluno (usuario) WHERE excluido = FALSE;
CREATE UNIQUE INDEX uk_aluno_email_ativo ON aluno (email) WHERE excluido = FALSE;
CREATE UNIQUE INDEX uk_ano_letivo_aluno_ano_ativo ON ano_letivo (aluno_id, ano) WHERE excluido = FALSE;
CREATE UNIQUE INDEX uk_disciplina_ano_letivo_nome_ativo ON disciplina (ano_letivo_id, nome) WHERE excluido = FALSE;

CREATE INDEX idx_ano_letivo_aluno_id ON ano_letivo (aluno_id);
CREATE INDEX idx_disciplina_ano_letivo_id ON disciplina (ano_letivo_id);
CREATE INDEX idx_tarefa_disciplina_id ON tarefa (disciplina_id);
CREATE INDEX idx_tarefa_status ON tarefa (status);
CREATE INDEX idx_tarefa_disciplina_status ON tarefa (disciplina_id, status);
CREATE INDEX idx_tarefa_data_prevista_entrega ON tarefa (data_prevista_entrega);
